increase modularity of infer_cp_features
cytomining/pycytominer pull request #103
Opened 2020-09-29 18:23 UTC by hillsbury

closes #81

2020-09-29 21:48 UTC, hillsbury commented
@gwaygenomics i changed up the tests and should be ready for review now

2020-09-30 10:41 UTC, gwaygenomics requested changes
Looks great @hillsbury - I proposed one small suggestion. Once committed and tests pass, I will approve the PR and we'll get this change merged into master 🎊

2020-09-30 10:41 UTC, gwaygenomics commented on pycytominer/cyto_utils/features.py
> +                features.append(col)
Looks great @hillsbury - I've proposed a small change below to make the code more [pythonic](https://docs.python-guide.org/writing/style/).

```suggestion
        if any([col.startswith(x.title()) for x in compartments]):
            features.append(col)
```

I didn't test this, but I think it should work

2020-09-30 10:41 UTC, gwaygenomics commented on pycytominer/tests/test_cyto_utils/test_feature_infer.py
> +def test_feature_infer_compartments():
🎉

2020-10-01 15:22 UTC, gwaygenomics commented
Looks great @hillsbury - I will go ahead and approve+merge

2020-10-01 15:22 UTC, gwaygenomics approved these changes

2020-10-01 15:22 UTC, merged