Fix #192 warnings for scipy mad func and other deprecated params
cytomining/pycytominer pull request #194
Opened 2022-05-04 15:07 UTC by johnarevalo

# Description

Change deprecated methods from external libraries.

## What is the nature of your change?

- [x] Bug fix (fixes an issue).
- [ ] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

# Checklist

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have deleted all non-relevant text in this pull request template.

2022-05-04 17:59 UTC, johnarevalo commented on pycytominer/operations/transform.py
> +            median_abs_deviation(X, nan_policy="omit", scale=1/1.4826), index=self.median.index
The `scale` param is required to preserve previous behavior. More info at [scipy doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.median_absolute_deviation.html#scipy.stats.median_absolute_deviation)

2022-07-08 20:33 UTC, johnarevalo commented
@gwaybio . This PR is ready. 5 warnings still persist. Two are related to `np.corrcoef` in constant columns, expected (?).

I found the remainder three harder to fix. This method is generating  duplicated column names when `pd.merge` with suffixes.

https://github.com/cytomining/pycytominer/blob/b4d32d39534c949ad5165f0b98b79537c2a7ca58/pycytominer/cyto_utils/cells.py#L604

2022-07-08 22:08 UTC, gwaybio requested changes
One inline comment.

The merge error is interesting. In your digging, did you notice any more details about what was going on? Is it safe to ignore this warning (pasted below)? (It's the first time I'm seeing it, to be honest)

```bash
 pycytominer/tests/test_cyto_utils/test_cells.py::test_merge_single_cells
  /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pandas/core/frame.py:9203: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ObjectNumber_cytoplasm'} in the result is deprecated and will raise a MergeError in a future version.
    validate=validate,
```

Given that 5 errors still persist, and @shntnu opened #192, I think he should have a say in how we proceed.

A couple other notes that might help our decision:

- We're moving away from the `SingleCells().merge_single_cells()` functionality, and solving this future error might not be necessary (unless the warning is pointing to some logic error! 😬 )
- We're also moving away from sqlalchemy, and same comment about these other 3 errors.
- My vote for how to proceed is to merge after addressing comments, but Shantanu, please chime in if you have any other concerns.

2022-07-11 16:40 UTC, johnarevalo commented
Thanks for this review Greg.

> did you notice any more details about what was going on?

IIUC `merge_single_cells` method expects certain naming convention generated by pandas to address duplicate column names after merging two DataFrames (e.g. add `_a` and `_b` suffixes). Future pandas will not resolve duplicate columns issues, but will raise an error instead.

> We're moving away from the SingleCells().merge_single_cells() functionality, and solving this future error might not be necessary (unless the warning is pointing to some logic error! 😬 )

I'd expect this too. Removing such method would solve this warning.

2022-08-01 23:05 UTC, gwaybio commented
Sorry for my delay in getting back to this (it dropped off the radar, to be honest!). Off the radar until today when @axiomcura noted an error in his pycytominer testing (and [pycytominer's requirements for scipy =>=1.3](https://github.com/cytomining/pycytominer/blob/b4d32d39534c949ad5165f0b98b79537c2a7ca58/requirements.txt#L2)). Thanks for your detective work Erik!

It seems that this PR will fix this error, and keep our scipy requirements up-to-date

It seems to me that we're all set to merge this in after Shantanu's 👍 :

> > My vote for how to proceed is to merge after addressing comments, but Shantanu, please chime in if you have any other concerns.

> I like this plan

----
p.s. - I opened #217 to capture Shantanu's sleuthing in https://github.com/cytomining/pycytominer/pull/194#issuecomment-1180781387

2022-08-01 23:06 UTC, gwaybio approved these changes

2022-08-01 23:06 UTC, merged