build(python): bump minimum Python version to 3.9
cytomining/pycytominer pull request #464
Opened 2024-10-29 16:09 UTC by d33bs

# Description

This PR bumps the minimum Python version required by Pycytominer to 3.9 (3.8 will no longer be compatible). [Python 3.8 is end-of-life](https://devguide.python.org/versions/) as of this month and there are related dependency issues which could possibly be resolved by removing Python 3.8 as a minimum version.

Thanks for any feedback!

Closes #433 

## What is the nature of your change?

- [ ] Bug fix (fixes an issue).
- [x] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have deleted all non-relevant text in this pull request template.

2024-10-29 16:26 UTC, kenibrewer requested changes
@d33bs Can you update [this line ](https://github.com/cytomining/pycytominer/blob/e8880bc68bf509e6f3db56dba672c86aee4b52dd/pyproject.toml#L120)
to `py39` and rerun ruff for the new changes?

2024-10-29 16:29 UTC, gwaybio approved these changes
great to see! Let's also see if @kenibrewer has any comments. 

@d33bs - is it worth also addressing #435 here (or soon)?

2024-10-29 17:14 UTC, d33bs commented
> Can you update [this line](https://github.com/cytomining/pycytominer/blob/e8880bc68bf509e6f3db56dba672c86aee4b52dd/pyproject.toml#L120)
to py39 and rerun ruff for the new changes?

Thanks @kenibrewer ! I've just added changes which bump the `ruff` target version and make related typing changes.

> @d33bs - is it worth also addressing https://github.com/cytomining/pycytominer/issues/435 here (or soon)?

Thanks @gwaybio ! My feeling is that Python 3.12 could possibly have surprises for us that lead to more complex changes or decision-making (I don't know of anything off-hand, but I expect something could pop up). This might be over-doing it, but as a result, I think it might be good to keep those changes in an adjacent PR.

2024-10-30 08:13 UTC, kenibrewer approved these changes

2024-10-30 08:14 UTC, merged